version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.3
      - image: redis:3.0.7
      - image: postgres:9.4.10
        environment:
          POSTGRES_USER: root
      - image: selenium/standalone-chrome
    working_directory: /cyb
    environment:
      RAILS_ENV: test
      RACK_ENV: test

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y apt-transport-https build-essential postgresql-contrib software-properties-common memcached unzip xvfb

      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | bash -
            apt-get install -y nodejs
      - run:
          name: Install Foreman
          command: |
            gem install foreman
      - run:
          name: Bundling and NPM install
          command: |
            bundle install
            npm install
            npm run webpack:build
      - run:
          name: Create & migrate DB
          command: |
            export RAILS_ENV="test"
            export RACK_ENV="test"
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
      - run:
          name: Install latest version of Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
            apt-get update -qq
            apt-get install -y google-chrome-stable
      - run:
          name: Install latest version of ChromeDriver
          command: |
            wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            rm chromedriver_linux64.zip
            mv chromedriver /usr/bin/
      - run:
          name: Running X virtual framebuffer
          command: Xvfb -ac :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1
          background: true
            - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test