version: 2
jobs:
  build:
    working_directory: ~/build
    environment:
        - buildenv: dev
    machine:
        image: circleci/classic:edge
    steps:
        - checkout
        - run:
             name: Build and Run Sema4 Testsuite
             shell: /bin/bash
             command: |
                  sudo su
                  sudo echo "18.220.45.66 lplus-qa.sema4genomics.com" >/etc/hosts
                  exit
                  cd $CIRCLE_PROJECT_REPONAME
                  mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml


   